// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Orders.Data.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260210185017_AddingOrderStates")]
    partial class AddingOrderStates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Orders.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Orders.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Domain.Orders.Entities.Order", b =>
                {
                    b.OwnsOne("Domain.Orders.Entities.OrderBillingInfo", "Billing", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("BilledAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("billing_billed_at");

                            b1.Property<Guid?>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("billing_invoice_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_status");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Domain.Orders.Entities.OrderCustomerInfo", "Customer", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("customer_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("customer_name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("customer_phone");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Domain.Orders.Entities.OrderAddressInfo", "Address", b2 =>
                                {
                                    b2.Property<Guid>("OrderCustomerInfoOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AdditionalInformation")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("customer_address_additionalinformation");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("customer_address_city");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("customer_address_number");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("customer_address_street");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("customer_address_zipcode");

                                    b2.HasKey("OrderCustomerInfoOrderId");

                                    b2.ToTable("Orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderCustomerInfoOrderId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.Orders.Entities.OrderOperationsInfo", "Operations", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("OperatorName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("operations_operator_name");

                            b1.Property<DateTime?>("PackedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("operations_packed_at");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Domain.Orders.Entities.OrderPaymentInfo", "Payment", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("payment_amount");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("payment_id");

                            b1.Property<DateTime?>("PaidAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("payment_paid_at");

                            b1.Property<string>("ProviderTransactionId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("payment_provider_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("payment_status");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Domain.Orders.Entities.OrderShippingInfo", "Shipping", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Carrier")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_carrier");

                            b1.Property<DateTime?>("DeliveredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("shipping_delivered_at");

                            b1.Property<string>("DestinationAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_destination_address");

                            b1.Property<DateTime?>("ReadyForPickupAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("shipping_ready_for_pickup_at");

                            b1.Property<DateTime?>("ShippedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("shipping_shipped_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_status");

                            b1.Property<string>("TrackingNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_tracking_number");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Domain.Orders.Entities.OrderStockReservationInfo", "Stock", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("CommittedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("stock_committed_at");

                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid")
                                .HasColumnName("stock_reservation_id");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Billing")
                        .IsRequired();

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Operations")
                        .IsRequired();

                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("Shipping")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Orders.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Orders.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Orders.Entities.Product", "Product", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CategoryName")
                                .HasColumnType("text")
                                .HasColumnName("product_category");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("product_description");

                            b1.Property<Guid>("ID")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<string>("Image")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("product_image");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("product_name");

                            b1.Property<float>("Price")
                                .HasColumnType("real")
                                .HasColumnName("product_price");

                            b1.Property<int>("Stock")
                                .HasColumnType("integer")
                                .HasColumnName("product_stock");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Orders.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
