using Core.Domain.Entities;

namespace Core.Domain.Commands;

/// <summary>
/// Command message used to initiate the order saga.  This message
/// contains the information required to create an order and begin
/// orchestration with downstream services (stock, payment, etc.).  The
/// CorrelationId will be used by MassTransit to track the saga state.
/// </summary>
public class SubmitOrder
{
    /// <summary>
    /// Gets or sets the identifier that correlates the saga.  This value is
    /// generated by the client submitting the order and is used by the
    /// state machine to uniquely identify each order orchestration.
    /// </summary>
    public Guid OrderId { get; set; }

    /// <summary>
    /// Gets or sets the identifier of the customer placing the order.
    /// </summary>
    public Guid CustomerId { get; set; }

    /// <summary>
    /// Gets or sets the collection of items being ordered.  Each item
    /// contains a product identifier and quantity.
    /// </summary>
    public List<Item> Items { get; set; } = new();
}