name: eshopacademy

services:

# Order Service
  order-api:
    container_name: order-api
    image: order-api
    build:
      context: ..
      dockerfile: OrderService/Presentation/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=31234358-e1e6-40e9-82fe-363a97801e4e
      - AZURE_CLIENT_SECRET=piI8Q~iaVPv30ukYTzBXKUi4FTaxoxglI4.Buapp
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
     - "8003:8080"
    networks:
     - backend
    depends_on:
     - order-db

  order-db:
    container_name: order-db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "8013:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend 


# Product Catalog Service
  product-api:
    container_name: product-api
    image: product-api
    build:
      context: ..
      dockerfile: ProductCatalogService/Presentation/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=facc151c-6753-4101-9035-e10cc34a38f3
      - AZURE_CLIENT_SECRET=Dsq8Q~D6TAdUK9VBKYM.M67LpDyZ_kS210.33cE3
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8001:8080"
    networks:
      - backend
    depends_on:
      - product-db
  
  product-db:
    container_name: product-db
    image: cassandra
    ports:
      - "8011:7000"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - backend

  # product-grpc:
  #   container_name: product-grpc
  #   image: product-grpc
  #   build:
  #     context: ..
  #     dockerfile: ProductCatalogService/Presentation/gRPC/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - KEYVAULT=eshopacademy
  #     - APPCONFIGURATION=eshopacademy
  #     - AZURE_CLIENT_ID=facc151c-6753-4101-9035-e10cc34a38f3
  #     - AZURE_CLIENT_SECRET=Dsq8Q~D6TAdUK9VBKYM.M67LpDyZ_kS210.33cE3
  #     - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
  #   ports:
  #     - "8021:8080"
  #   networks:
  #     - backend
  #   depends_on:
  #     - product-db


# Basket Service
  basket-api:
    container_name: basket-api
    image: basket-api
    build:
      context: ..
      dockerfile: BasketService/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=3bef33a0-5cd1-49b3-ab3b-2291145e3f2c
      - AZURE_CLIENT_SECRET=DQe8Q~K8gDgM3vHpokpgrW3lD8au~igTkZQCxape
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8004:8080"
    networks:
      - backend
    depends_on:
      - basket-db

  basket-db:
    container_name: basket-db
    image: redis
    ports:
      - "8014:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
       
  basket-processor:
    container_name: basket-processor
    image: basket-processor
    build:
      context: ..
      dockerfile: BasketService/EventsProcessor/EventsProcessor/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=3bef33a0-5cd1-49b3-ab3b-2291145e3f2c
      - AZURE_CLIENT_SECRET=DQe8Q~K8gDgM3vHpokpgrW3lD8au~igTkZQCxape
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8024:8080"
    networks:
      - backend
    depends_on:
      - basket-db


# Stock Service
  stock-api:
    container_name: stock-api
    image: stock-api
    build:
      context: ..
      dockerfile: StockService/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=f8414e0b-f3fc-417e-9579-dcf2522d012f
      - AZURE_CLIENT_SECRET=5ou8Q~aiomsSKzKOQo89Eg6O4uKInhC2rM3fncCW
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8002:8080"
    networks:
      - backend
    depends_on:
      - stock-db

  stock-db:
    container_name: stock-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
    networks:
      - backend
    volumes:
      - mongo_data:/data/db
    ports:
      - "8012:27017"
 
  # stock-grpc:
  #   container_name: stock-grpc
  #   image: stock-grpc
  #   build:
  #     context: ...
  #     dockerfile: StockService/gRPC/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - KEYVAULT=eshopacademy
  #     - APPCONFIGURATION=eshopacademy
  #     - AZURE_CLIENT_ID=f8414e0b-f3fc-417e-9579-dcf2522d012f
  #     - AZURE_CLIENT_SECRET=5ou8Q~aiomsSKzKOQo89Eg6O4uKInhC2rM3fncCW
  #     - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
  #   ports:
  #     - "8022:8080"
  #   networks:
  #     - backend
  #   depends_on:
  #     - stock-db


# Payment Service
  #payment-grpc
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development
    #   - ASPNETCORE_HTTP_PORTS=8080
    #   - KEYVAULT=eshopacademy
    #   - APPCONFIGURATION=eshopacademy
    #   - AZURE_CLIENT_ID=4ac9deea-ea6d-4794-8414-dfae912b50a2
    #   - AZURE_CLIENT_SECRET=gM88Q~-WrvT.yyZA8exq~kC6ydUTQqBZWDPioaEx
    #   - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed


# Shipping Service
  #shipping-grpc
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development
    #   - ASPNETCORE_HTTP_PORTS=8080
    #   - KEYVAULT=eshopacademy
    #   - APPCONFIGURATION=eshopacademy
    #   - AZURE_CLIENT_ID=bdcf29bc-ebed-428f-9b86-e3d84d9a2314
    #   - AZURE_CLIENT_SECRET=ceL8Q~xXDZOCEjzSCB16Gv-cpDQxy7iKNcT6-cxX
    #   - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed


# Notification Service
  #notification-processor
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development
    #   - ASPNETCORE_HTTP_PORTS=8080
    #   - KEYVAULT=eshopacademy
    #   - APPCONFIGURATION=eshopacademy
    #   - AZURE_CLIENT_ID=9f12ad1b-0f88-4a7b-aa38-f1590b9137e3
    #   - AZURE_CLIENT_SECRET=NsA8Q~49rqxcw_OyUxjREY~UQfV4unrj6i5hHdpb
    #   - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed


# API Gateway
  #gateway-api
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development
    #   - ASPNETCORE_HTTP_PORTS=8080
    #   - KEYVAULT=eshopacademy
    #   - APPCONFIGURATION=eshopacademy
    #   - AZURE_CLIENT_ID=a99cca94-1c53-4565-b482-06fe21eea113
    #   - AZURE_CLIENT_SECRET=ct~8Q~TpjNLCXhVfNLzVnybFt2bgNIDgKR1CtcNm
    #   - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed

    
# Infrastructure

volumes:
  redis_data:
  cassandra_data:
  mongo_data:
  postgres_data:
  
networks:
  backend:
    driver: bridge
  

