name: eshopacademy
version: '3.4'

services:

# Product Catalog Service
  product-api:
    container_name: product-api
    image: product-api
    build:
      context: .
      dockerfile: ../ProductCatalogService/Presentation/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=5e6023bb-fc90-4cd5-83b8-c503da5f2c59
      - AZURE_CLIENT_SECRET=GSD8Q~EoxyueAtyR9MHaymFnx1L1bm-ysbEetcm.
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8001:8080"
    networks:
      - backend
    depends_on:
      - product-db
      - rabbitmq
  
  product-db:
    container_name: product-db
    image: cassandra
    ports:
      - "8011:7000"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - backend

  product-grpc:
    container_name: product-grpc
    image: product-grpc
    build:
      context: .
      dockerfile: ../ProductCatalogService/Presentation/gRPC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=bddb1a06-cfd9-4524-bfde-7f4d4d485288
      - AZURE_CLIENT_SECRET=XvV8Q~kdKRmlp.jx~VVuUm4jyTnh2rtm1b5Jlc.W
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8021:8080"
    networks:
      - backend
    depends_on:
      - product-db
      - rabbitmq


# Basket Service
  basket-api:
    container_name: basket-api
    image: basket-api
    build:
      context: .
      dockerfile: ../BasketService/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=27f4c9a6-b8b1-444a-89f4-aa0af25967eb
      - AZURE_CLIENT_SECRET=rMZ8Q~Ho0DtF2D9Wk.oZ4bXQYXEJWEB4rMGlIbJt
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8004:8080"
    networks:
      - backend
    depends_on:
      - basket-db

  basket-db:
    container_name: basket-db
    image: redis
    ports:
      - "8014:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
       
  basket-processor:
    container_name: basket-processor
    image: basket-processor
    build:
      context: .
      dockerfile: ../BasketService/EventsProcessor/EventsProcessor/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=d7226736-7a38-493a-8a3c-40304c73a360
      - AZURE_CLIENT_SECRET=jfE8Q~JfRsMU5SV.jRE1T09r~NJT6A_8Nw-4xaq0
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8024:8080"
    networks:
      - backend
    depends_on:
      - basket-db
      - rabbitmq

# Stock Service
  stock-api:
    container_name: stock-api
    image: stock-api
    build:
      context: ..
      dockerfile: StockService/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=0df6486c-5f73-43ea-acb9-2e8a1a1ed6b3
      - AZURE_CLIENT_SECRET=f_R8Q~xlJn0Epd7gfvVfzy~zfZpfiiTl-0h.4aEE
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8002:8080"
    networks:
      - backend
    depends_on:
      - stock-db
      - rabbitmq

  stock-db:
    container_name: stock-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
    networks:
      - backend
    volumes:
      - mongo_data:/data/db
    ports:
      - "8012:27017"

  stock-grpc:
    container_name: stock-grpc
    image: stock-grpc
    build:
      context: ..
      dockerfile: StockService/gRPC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - KEYVAULT=eshopacademy
      - APPCONFIGURATION=eshopacademy
      - AZURE_CLIENT_ID=f30904f9-ae20-4f3e-b8ed-da3751283fc0
      - AZURE_CLIENT_SECRET=Xfk8Q~2xwOLJrXsZVpxTyX-qLSt4VFyuL0BWNcf2
      - AZURE_TENANT_ID=82abd0e4-97e7-4ad4-9b49-4c93188625ed
    ports:
      - "8022:8080"
    networks:
      - backend
    depends_on:
      - stock-db
      - rabbitmq

# Order Service
  order-db:
    container_name: order-db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "8013:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

# Infrastructure
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5673:5673"
    networks:
      - backend
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
 

volumes:
  redis_data:
  cassandra_data:
  mongo_data:
  postgres_data:
  rabbitmq_data:
  
networks:
  backend:
  