FROM mcr.microsoft.com/devcontainers/dotnet:8.0
RUN apt-get update && apt-get install -y --no-install-recommends git curl ca-certificates unzip && rm -rf /var/lib/apt/lists/*
WORKDIR /workspaces/eShopAcademy
