name: dotnet-ci

on:
  push:
    branches: [ main-lucas, feature/** ]
  pull_request:
    branches: [ main-lucas ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Authenticate to GitHub Packages
        run: dotnet nuget update source github --username LucasLoFaro --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --configfile src/NuGet.config
      - name: Restore
        run: dotnet restore src/eShopAcademy.sln
      - name: Build
        run: dotnet build src/eShopAcademy.sln -c Release --no-restore
      - name: Test
        run: dotnet test src/eShopAcademy.sln -c Release --no-build --logger "trx;LogFileName=TestResults.trx"
